### PR TITLE
New policy to handle "?" objects

### PR DESCRIPTION
**Pull request by pattacini**
### Old policy
For each segmented blob, do:
1. Compute the maximum score to get the most likely category;
1. Check that for all the other blobs it holds that the score corresponding to that category is lower. If the check fails, mark the blob as "?".

### New policy
For each segmented blob, do:
1. Compute the maximum score to get the most likely category;
1. Neglect all the other blobs and focus on the current blob, for which the remaining categories shall have scores lower than `0.75*maxScore`. If the check fails, mark the blob as "?".

@vtikha @giuliavezzani

### CODE REVIEW

**Comment by pattacini** [comment]
Blacky's setup updated.

**Comment by vtikha** [comment]
Excellent, thanks @pattacini will do all necessary tests asap

**Comment by giuliavezzani** [comment]
Thank you so much @pattacini!

**Comment by giuliavezzani** [comment]
The behavior of the demo is now the desired one:

cylinder-iol

If multiple cylinders are shown, all of them are labeled correctly.

Thanks @pattacini!

**Pull request merged**
