### PR TITLE
Added 'This is $Object' command to teach objects faster

### PR DESCRIPTION
**Pull request by cciliber**
I have added a new functionality to allow to teach objects during the demo without iterating between the human and the robot. 

Case scenario: the user points at an object and says `This is a <obj_name>`. Then the robot learns the object accordingly. Different cases are handled appropriately (e.g. Misclassification, Already known object or unknown object).

Video: https://goo.gl/photos/mG4PxCGhW8Ytoc2K9

Thanks @alecive!

### CODE REVIEW

**Comment by pattacini** [comment]
Great! That's a useful command indeed.
The video is funny :smile:

**Comment by pattacini** [comment]
@alecive we need then to update `lua` scripts for `yarpdroid`

**Comment by pattacini** [comment]
@alecive It was simple actually; I've done it with https://github.com/robotology/iol/commit/bb7536689459f5004b6c0d488813d573a2fa9cb9.

**Comment by lornat75** [comment]
+1

**Comment by cciliber** [comment]
Ops, I did it too but did not commit yet.
I guess I'll just ranz mine

**Comment by pattacini** [comment]
@cciliber before _ranzing_, please double check if I did the job right :smirk:

**Pull request merged**
